language: node_js
node_js:
- lts/*
after_success:
- "./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls"
sudo: false
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: AqCoW/I3rcAx6Kj0IxVKB/Iny4kuqh6c7Isnrfj2nmTV0X/FTiLg1zjQA3EamqfrUq+yFH0C0XwFKowm8o16v4qxMHuNWwq59Wf/r90NgXajlt8sArtJC2I3HB/V2GHE3TAnV/Sq3HqidclEGT0XkxqNJsRtBp42lzrRnvVqBu83t4l37Am74NjI3UDBQTPA+qb4xWOiUZokPXXlbsa8xyJBPFKG7vkWvXgFvwhvpRziIk5JkjyMBKVI36HUUlg1t/qtj/mZmPtS5bQ2vZ2kS/1oCKXblqFQxNxJgay6EmEUREECjJDDiKXKmzy9ZUUIcspfvRZGMsP60VqQa+N793w1XUvkHo5aKKRptvOSrkFBO6t1UNhu1ErgUWb0gS0LMbFafZa8211zVAgFRStFAX/koqw4KAVmSmNHa/6OH2BFD32MWLO16PmoFT6fLXu0lmjrWYaZXIFAh4WmN6AJjh3FM8yAbbi5KFIIn5nMI6SeupzPAziEZqQltTY+MbNs7zoISWq4FtrjuZ5VqkvC8IRKc7mE+RypWFEjzszydJ+sdUcjRg4NhUIo+tohCIO6ay9i98rYUafNJMX2y8C5MnMGNS3v9qFq5zN4Ve6cbDK6kee8NcgEO0VS99iKUZHmvpWLUwDyaoOMLgsxcKw5QbACwZM32UHZI76pyATsPZU=
  on:
    tags: true
    repo: noflo/noflo-swagger-client
  skip_cleanup: 'true'
